name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - develop
      - staging

  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.9"
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build DEV APK
        if: github.ref == 'refs/heads/develop'
        run: |
          flutter build apk \
            --flavor dev \
            --release \
            --dart-define=ENVIRONMENT=dev

      - name: Build STAGING APK
        if: github.ref == 'refs/heads/staging'
        run: |
          flutter build apk \
            --flavor staging \
            --release \
            --dart-define=ENVIRONMENT=staging

      - name: Decode Android keystore
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks

      - name: Create key.properties
        if: github.ref == 'refs/heads/main'
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - name: Build PROD AAB
        if: github.ref == 'refs/heads/main'
        run: |
          flutter build appbundle \
            --flavor prod \
            --release \
            --dart-define=ENVIRONMENT=prod

      - name: Upload DEV APK
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: flutter-dev-apk
          path: build/app/outputs/flutter-apk/app-dev-release.apk

      - name: Upload STAGING APK
        if: github.ref == 'refs/heads/staging'
        uses: actions/upload-artifact@v4
        with:
          name: flutter-staging-apk
          path: build/app/outputs/flutter-apk/app-staging-release.apk

      - name: Upload PROD AAB
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: flutter-prod-aab
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab
